### Done to remove biasness form the data. Techniques are Upsampling and Downsampling.

In [ ]:
# 1. UpSampling & DownSampling

import numpy as np
import pandas as pd

# set the random seed for reporducibility
np.random.seed(123)


# creating a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [6]:
n_class_0, n_class_1

(900, 100)

In [7]:
# creating a imbalance dataset

class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale = 1, size = n_class_0),
    'feature_2' : np.random.normal(loc=0, scale = 1, size = n_class_0),
    'target' : [0] * n_class_0
    
})

class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2, scale = 1, size = n_class_1),
    'feature_2' : np.random.normal(loc=2, scale = 1, size = n_class_1),
    'target' : [1] * n_class_1
    
})

In [11]:
df = pd.concat([class_0, class_1]).reset_index(drop = True)

In [12]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [13]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [14]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [15]:
# using upsampling now
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [16]:
from sklearn.utils import resample
df_minority_upsampling = resample(df_minority, replace = True #samples with replacement
         , n_samples = len(df_majority)
         ,random_state = 42)

In [18]:
df_minority_upsampling.shape

(900, 3)

In [19]:
df_minority_upsampling.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [21]:
df_upsampled = pd.concat([df_majority, df_minority_upsampling])

In [23]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [24]:
# DownSampling now
# creating a imbalance dataset

class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale = 1, size = n_class_0),
    'feature_2' : np.random.normal(loc=0, scale = 1, size = n_class_0),
    'target' : [0] * n_class_0
    
})

class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2, scale = 1, size = n_class_1),
    'feature_2' : np.random.normal(loc=2, scale = 1, size = n_class_1),
    'target' : [1] * n_class_1
    
})

In [25]:
df = pd.concat([class_0, class_1]).reset_index(drop = True)

In [26]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
# using downsampling now
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [28]:
from sklearn.utils import resample
df_majority_downsampling = resample(df_majority, replace = False  # because we have to remove the datapoints and not add it
         , n_samples = len(df_minority)
         ,random_state = 42)

In [30]:
df_majority_downsampling.shape

(100, 3)

In [32]:
df_downsampled = pd.concat([df_minority,df_majority_downsampling])

In [33]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64

In [34]:
df_downsampled.head()

     feature_1  feature_2  target
900  -0.643425   2.571923       1
901   1.551009   1.782767       1
902   1.641093   2.054318       1
903   2.133194   2.155998       1
904   1.355758   2.467810       1

In [36]:
df_downsampled.tail()

     feature_1  feature_2  target
398   1.013666   0.083496       0
76    0.164480  -1.808980       0
196  -1.576624   0.525893       0
631  -0.540147   0.610282       0
751  -0.168798  -0.831334       0