# Label Encoding

### Assigning a unique numerical label to each category in a variable.

In [2]:
import pandas as pd

In [11]:
# create a simple DataFrame
df = pd.DataFrame({
    'color' : ['red','blue','green','yellow','red','blue']
})

In [12]:
df.head()

    color
0     red
1    blue
2   green
3  yellow
4     red

In [13]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [14]:
lbl_encoder.fit_transform(df[['color']])

/home/prashant/practice/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 3, 2, 0])

In [17]:
lbl_encoder.transform([['green']])

/home/prashant/practice/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [19]:
lbl_encoder.transform([['red']])

/home/prashant/practice/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

# Ordinal Encoding

### used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value bases on its position in the order. It assigns ranks to the features.

In [3]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'small', 'large']
})

In [5]:
df

     size
0   small
1  medium
2   large
3   small
4   large

In [6]:
# assigning ranking now
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.]])

In [8]:
encoder.transform([['small']])

/home/prashant/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])