# Used Car Price Prediction
## 1) Problem statement.

This dataset comprises used cars sold on cardheko.com in India as well as important features of these cars.

If user can predict the price of the car based on input features.

Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.

The Dataset is collected from scrapping from cardheko website.

The data consists of 13 column and 15411 rows.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('cardekho_imputated.csv', index_col= 0)

In [3]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
# Data Cleaning
# Handling missing values
# Handling duplicates
# Check data type
# Understand the dataset

df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [5]:
# Removing Unnecessary columns
df.drop(columns=['car_name', 'brand'], axis = 1, inplace = True)

In [6]:
df.sample(5)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
18761,E-Class,15,78000,Dealer,Petrol,Automatic,10.50,1796,157.7,5,500000
19293,Swift,3,17000,Dealer,Petrol,Automatic,21.21,1197,81.8,5,765000
5798,Swift Dzire,6,75137,Dealer,Diesel,Manual,26.59,1248,74.0,5,475000
18127,Santro,12,110000,Individual,LPG,Manual,13.45,1086,62.1,5,200000
18894,KWID,3,50000,Individual,Petrol,Manual,25.17,799,53.3,5,300000

In [7]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [8]:
# Getting all different types of features
num_features = [features for features in df.columns if df[features].dtypes != 'O']
print('Number of numerical features : ', len(num_features))

cat_features = [features for features in df.columns if df[features].dtypes == 'O']
print('Number of categorical features : ', len(cat_features))

dis_features = [features for features in num_features if len(df[features].unique()) <= 25]
print('Number of discrete features : ', len(dis_features))

con_features = [features for features in num_features if features not in dis_features]
print('Number of continous features : ', len(con_features))

Number of numerical features :  7
Number of categorical features :  4
Number of discrete features :  2
Number of continous features :  5

In [9]:
# Independent and Dependent features
from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'], axis = 1)
y = df['selling_price']

In [10]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [11]:
y.head()

0    120000
1    550000
2    215000
3    226000
4    570000
Name: selling_price, dtype: int64

# Feature Encoding and Scaling

One Hot Encoding for columns which had lesser unique values and not ordinal

In [12]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [14]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [15]:
X['fuel_type'].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [16]:
# create column transformer with 3 types of transformation
num_features = X.select_dtypes(exclude='object').columns
cat_features = ['seller_type', 'fuel_type', 'transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

num_transformer = StandardScaler()
cat_transformer = OneHotEncoder(drop = 'first')

preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder', cat_transformer, cat_features),
        ('StandardScalar', num_transformer, num_features)
    ], remainder= 'passthrough'
)

In [17]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [18]:
X = preprocessor.fit_transform(X)

In [19]:
X

array([[ 1.        ,  0.        ,  0.        , ..., -1.32425883,
        -1.26335238, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43257082, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.47911321, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.02291783,
         0.06822523, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  1.32979434,
         0.91715831,  2.07344426],
       [ 0.        ,  0.        ,  0.        , ...,  0.02099878,
         0.39588361, -0.40302241]], shape=(15411, 14))

In [20]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [21]:
#Separating dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((10787, 14), (10787,), (4624, 14), (4624,))

# Model Training & Model Selection

In [22]:
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [23]:
##Create a Function to Evaluate Model
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [24]:
# Begin model training
models ={
    'Ada boost Regression': AdaBoostRegressor(),
    'Gradeint boosting Regression': GradientBoostingRegressor(),
    'Linear Regression': LinearRegression(),
    'Lasso': Lasso(),
    'Ridge': Ridge(),
    'K Nearest Regressor' : KNeighborsRegressor(),
    'Decision Tree Regressord': DecisionTreeRegressor(),
    'Random Forest Classifier': RandomForestRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test Dataset
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

Ada boost Regression
Model performance for Training set
- Root Mean Squared Error: 440184.8179
- Mean Absolute Error: 326080.6505
- R2 Score: 0.7636
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 517297.4481
- Mean Absolute Error: 353893.1549
- R2 Score: 0.6442
===================================


Gradeint boosting Regression
Model performance for Training set
- Root Mean Squared Error: 196643.0742
- Mean Absolute Error: 110110.8637
- R2 Score: 0.9528
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 279446.2422
- Mean Absolute Error: 129406.4126
- R2 Score: 0.8962
===================================


Linear Regression
Model performance for Training set
- Root Mean Squared Error: 559313.7144
- Mean Absolute Error: 268437.6549
- R2 Score: 0.6183
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 507556.7988
- Mean Absolute Error: 281329.9042
- R2 Score: 0.6575
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 559313.7247
- Mean Absolute Error: 268436.5960
- R2 Score: 0.6183
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 507555.9012
- Mean Absolute Error: 281329.3313
- R2 Score: 0.6575
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 559314.5337
- Mean Absolute Error: 268393.2589
- R2 Score: 0.6183
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 507539.4235
- Mean Absolute Error: 281276.8149
- R2 Score: 0.6575
===================================


K Nearest Regressor
Model performance for Training set
- Root Mean Squared Error: 338148.7903
- Mean Absolute Error: 91830.8149
- R2 Score: 0.8605
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 287899.8049
- Mean Absolute Error: 116755.5201
- R2 Score: 0.8898
===================================


Decision Tree Regressord
Model performance for Training set
- Root Mean Squared Error: 20329.7436
- Mean Absolute Error: 4728.8897
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 291208.7539
- Mean Absolute Error: 127180.2714
- R2 Score: 0.8872
===================================


Random Forest Classifier
Model performance for Training set
- Root Mean Squared Error: 143805.5146
- Mean Absolute Error: 40063.0523
- R2 Score: 0.9748
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 244705.0883
- Mean Absolute Error: 105465.9650
- R2 Score: 0.9204
===================================

# HyperParameter Tuning of best performing models

In [25]:
#Initialize few parameter for Hyperparamter tuning
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}


gradient_params={"loss": ['squared_error', 'huber', 'absolute_error'],
                 "criterion": ['friedman_mse', 'squared_error', 'mse'],
                 "min_samples_split": [2, 8, 15, 20],
                 "n_estimators": [100, 200, 500, 1000],
                 "max_depth": [5, 8, 15, None, 10],
                 "learning_rate": [0.1, 0.01, 0.001]}

In [26]:
# models list for hyper parameter tuning
randomcv_models = [('GradientBoosting', GradientBoostingRegressor(), gradient_params),
                   ('RF', RandomForestRegressor(), rf_params)]

In [27]:
# Hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator= model,
                                param_distributions= params,
                                n_iter = 10,
                                cv = 3,
                                verbose = 2)
    
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print (f'--------------Best Params for {model_name} ----------------')
    print(model_param[model_name])

Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] END criterion=mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=15, n_estimators=1000; total time=  11.8s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=15, n_estimators=1000; total time=  11.8s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=15, n_estimators=1000; total time=  12.1s
[CV] END criterion=mse, learning_rate=0.01, loss=squared_error, max_depth=None, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.01, loss=squared_error, max_depth=None, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.01, loss=squared_error, max_depth=None, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.01, loss=absolute_error, max_depth=15, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.01, loss=absolute_error, max_depth=15, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.01, loss=absolute_error, max_depth=15, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END criterion=mse, learning_rate=0.001, loss=squared_error, max_depth=10, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=8, min_samples_split=15, n_estimators=200; total time=   2.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=8, min_samples_split=15, n_estimators=200; total time=   2.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=8, min_samples_split=15, n_estimators=200; total time=   2.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=squared_error, max_depth=15, min_samples_split=8, n_estimators=100; total time=   1.6s
[CV] END criterion=squared_error, learning_rate=0.001, loss=squared_error, max_depth=15, min_samples_split=8, n_estimators=100; total time=   1.5s
[CV] END criterion=squared_error, learning_rate=0.001, loss=squared_error, max_depth=15, min_samples_split=8, n_estimators=100; total time=   1.6s
[CV] END criterion=squared_error, learning_rate=0.001, loss=squared_error, max_depth=15, min_samples_split=20, n_estimators=500; total time=   7.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=squared_error, max_depth=15, min_samples_split=20, n_estimators=500; total time=   7.2s
[CV] END criterion=squared_error, learning_rate=0.001, loss=squared_error, max_depth=15, min_samples_split=20, n_estimators=500; total time=   7.4s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=squared_error, max_depth=15, min_samples_split=20, n_estimators=500; total time=   7.5s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=squared_error, max_depth=15, min_samples_split=20, n_estimators=500; total time=   7.6s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=squared_error, max_depth=15, min_samples_split=20, n_estimators=500; total time=   7.9s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=huber, max_depth=5, min_samples_split=20, n_estimators=200; total time=   2.2s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=huber, max_depth=5, min_samples_split=20, n_estimators=200; total time=   2.2s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=huber, max_depth=5, min_samples_split=20, n_estimators=200; total time=   2.1s
Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=   1.9s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=   1.9s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=   1.9s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.5s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.5s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.9s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.9s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.4s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   1.5s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   1.6s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   1.6s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.6s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.6s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.6s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.3s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.3s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.3s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.1s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   2.2s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   2.2s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   2.2s
--------------Best Params for GradientBoosting ----------------
{'n_estimators': 500, 'min_samples_split': 20, 'max_depth': 15, 'loss': 'squared_error', 'learning_rate': 0.01, 'criterion': 'friedman_mse'}
--------------Best Params for RF ----------------
{'n_estimators': 100, 'min_samples_split': 2, 'max_features': 8, 'max_depth': 10}

In [28]:
# Retraining the models with the upper selected params
models = {
    "gradient boosting regressor": GradientBoostingRegressor(n_estimators= 500, min_samples_split= 20, max_depth= 15, loss= 'squared_error', learning_rate= 0.01, criterion= 'friedman_mse'),
    "random forest" : RandomForestRegressor(n_estimators= 100, min_samples_split= 2, max_features= 8, max_depth= 10)
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test Dataset
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

gradient boosting regressor
Model performance for Training set
- Root Mean Squared Error: 60508.7832
- Mean Absolute Error: 38440.1015
- R2 Score: 0.9955
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 247978.9166
- Mean Absolute Error: 104936.9001
- R2 Score: 0.9182
===================================


random forest
Model performance for Training set
- Root Mean Squared Error: 179658.5035
- Mean Absolute Error: 82718.1511
- R2 Score: 0.9606
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 245335.6282
- Mean Absolute Error: 108007.4308
- R2 Score: 0.9200
===================================